[package]
name = "dkim"
type = "bin"
authors = ["richardliang"]
compiler_version = "0.10.5"

[dependencies]
biguint = { path = "../../crates/rsa-biguint" }
rsa = { path = "../../crates/rsa" }
sha2 = { tag = "v0.0.1", git = "https://github.com/michaelelliot/noir-sha2", directory = "crates/noir-sha2" }